### ISSUE TITLE
problem parsing yaml anchors for completion report

### ISSUE THREAD

**Issue by yruss972** [jenglish/ssptool#17]
When creating a component which makes use of YAML anchors, the completion report doesn't parse the implementation_status properly, for example:
```yaml
satisfies:
  - standard_key: TSC
    control_key: CC1.1
    covered_by: &shared_responsibility_coverage
      - verification_key: AWS_SOC_2_REPORT
    implementation_status: &shared_responsibility_implemetation complete
    narrative: &shared_responsibility_narrative
      - text: |
          The latest SOC 2 report provided by AWS covers the service:
            AWS Certificate Manager (ACM)
          This control is sufficiently covered by AWS's reported controls.
  - standard_key: TSC
    control_key: CC1.2
    covered_by: *shared_responsibility_coverage
    implementation_status: *shared_responsibility_implemetation
    narrative: *shared_responsibility_narrative
```
Control CC1.1 is lists unknown for the completion status
Other controls show completion correctly.
