### ISSUE TITLE
Support satisfying a control only if multiple other controls are satisfied

### ISSUE THREAD

**Issue by yruss972** [jenglish/ssptool#18]
Assuming a certification mapping alternate standards like this:
```yaml
name: TSC
standards:
  TSC:
    CC6.1:
      mapping:
        MY-TSC:
          - CC6.1.1
          - CC6.1.2
```
This is interpreted so that any of the MY-TSC controls can satisfy the parent TSC control.

It would be cool if we could use a syntax like:
```yaml
name: TSC
standards:
  TSC:
    CC6.1:
      mapping:
        MY-TSC:
          - [CC6.1.1, CC6.1.2]
          - CC6.1.3
          - CC6.1.4
```
to say we if we satisfy (CC6.1.1 *AND* CC6.1.2) *OR* CC6.1.3 *OR* CC6.1.4), then we satisfy CC6.1

I'm not sure if there are any accepted patterns for how to do this in the YAML world- might be nice to specify the operator ie:
```yaml
name: TSC
standards:
  TSC:
    CC6.1:
      mapping:
        MY-TSC:
          - AND: [CC6.1.1, CC6.1.2]
          - OR: [CC6.1.3, CC6.1.4]
          - XOR: [CC6.1.0, CC6.1.1]
```
The AND would be very useful in rolling up controls which have been broken down.
The XOR would be useful in alternate exclusive controls, ie. MFA vs Two man rule, etc.
